### ISSUE TITLE
Tracking is not working 

### ISSUE THREAD

**Issue by zaynjl** [aniyomiorg/aniyomi#1017]
### Steps to reproduce

Tracking anime or manga
1. Add a tracking service such as ( MaL) or ( Anilist) 
2. Watch/ read an episode/ chapter 

### Expected behavior

Automatically adds the episode or chapter to the tracker

### Actual behavior

It's not doing anything, no matter if I watched or read anything 

### Crash logs

HTTP error 400

### Aniyomi version

0.12.3.10

### Android version

11

### Device

Samsung Galaxy A70

### Other details

I tried the preview version of the app and it doesn't even have the tracking future lol

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by LittleFreak** [comment]
Have you tried to remove the tracker from the settings and rr-login/add them?

**Comment by Th3-A6add0n** [comment]
Yup, doesn't work. Nothing shows up in the library.

**Comment by Quickdesh** [comment]
https://github.com/aniyomiorg/aniyomi/issues/1154
