### ISSUE TITLE
Tracking Data Will Not Auto-Select or Auto-Copy/Migrate Over When Manually Selected

### ISSUE THREAD

**Issue by Nav223** [aniyomiorg/aniyomi#1100]
### Steps to reproduce

1. Choose a series you wish to migrate or copy over to another extension.
2. Click Migrate on that series and then click which extension to migrate to for the pop-up.
3. Under "Select data to include" select Tracking if series is already being tracked on MAL, anilist, etc.
4. Issue is seen when Tracking data is not copied or migrated over to other extensions.
5. Can try copying/migrating again, but "Tracking" will not remain selected under "Select data to include" and will need to be manually selected again to try.

### Expected behavior

After selecting "Tracking" under "Select data to include" when copying or migrating a series to another extension, it should work and the pre-existing tracking data for MAL, anilist, etc., should be carried over to the extension selected. Also, "Tracking" should remain selected for the next time under "Select data to include" when you try to migrate or copy a series to another extension again.

### Actual behavior

Instead, the tracking option under "Select data to include" when copying or migrating a series to another extension does not remain selected, and the tracking data for a series also does not copy or migrate over when it is manually selected.

https://github.com/aniyomiorg/aniyomi/assets/93855434/70a4e2be-9272-4892-846d-a3742f4baaeb

### Aniyomi version

Preview r6151

### Android version

Android 13

### Device

Samsung S20 FE

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
Should be fixed
