### ISSUE TITLE
Tracker issue

### ISSUE THREAD

**Issue by Cxachella** [aniyomiorg/aniyomi#1197]
### Steps to reproduce

Could not add tracker to the anime/manga
Aniyomi version r6691
Hello, first of all thanks for providing this app. I am really grateful for such thing to exist. Secondly and finally, it seems that the trackers don't work (MyAnimeList in my case) because every time I try to add a tracker, it says error not found. Thanks again

### Expected behavior

It should show the anime I want to track

### Actual behavior

It says error 401

### Aniyomi version

r6691

### Android version

Android 12

### Device

Galaxy S10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/help/faq/) and [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Cxachella** [comment]
It worked, thank you :)
