### ISSUE TITLE
Anilist Tracker not updating

### ISSUE THREAD

**Issue by helpthecrepe** [aniyomiorg/aniyomi#1608]
### Steps to reproduce

1. Add anilist tracker
2. Read a manga chapter or watch an anime episode

### Expected behavior

The tracker should update every time i read a new chapter or watch an epsiode.

### Actual behavior

The tracker does not update every time i read a new chapter or watch an epsiode.

### Aniyomi version

Aniyomi Preview r7567

### Android version

Android 11

### Device

Samsung Galaxy S10+

### Other details

![Anilist not working](https://github.com/aniyomiorg/aniyomi/assets/86891798/cfb7f3a5-b758-42a2-b86c-890a43493b8e)

I can get the tracker to update by removing the tracker from the manga/anime and readding it. (very inconvenient to do it every single time and for every manga and anime).

Some extra stuff to not when readding the tracker to the manga or anime, anilist sometime doesn't work and I would have to relogin. (probably irrelevant and an issue by itself)

I have two tracker mal and aniyomi, mal updates fine sometime glitches(rarely) but apparently that's normal.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official anime extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with a manga extension, report it to the manga source extension project you added it from.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.3.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Unable to replicate. Make sure to log out and back in before trying again, otherwise it could be some temporary error on anilist's end
