### ISSUE TITLE
Tracker for Animeplanet

### ISSUE THREAD

**Issue by AO124** [aniyomiorg/aniyomi#473]
### Describe your suggested feature

Though there is already tracker for mal, anilsit and some other. But as planet user. I would request you to add animeplanet.com tracker. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Jjjggh** [comment]
Anime planet have things that the others don't

**Comment by Quickdesh** [comment]
There is no current existing API that we can use to develop a tracker
