### ISSUE TITLE
Add mydramalist tracking

### ISSUE THREAD

**Issue by suhan-paradkar** [aniyomiorg/aniyomi#544]
### Describe your suggested feature

Add support for tracking mydramalist entries

### Other details

Mydramalist provides an api to access their site...
More details can be found [here](https://mydramalist.github.io/MDL-API/)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MoonLGH** [comment]
ref : https://mydramalist.github.io/MDL-API/#introduction

**Comment by Quickdesh** [comment]
I had requested them for API key but have received no answer fora  good while now.
Until we receive a working API key, MDL tracker cannot be made

**Comment by sthasam2** [comment]
Hey guys, they seem to have updated their docs with new API schemas. Can we look into this?

**Comment by Azmarine13** [comment]
> Hey guys, they seem to have updated their docs with new API schemas. Can we look into this?

Why? Can you share the link to their official doc page?

**Comment by sthasam2** [comment]
> > Hey guys, they seem to have updated their docs with new API schemas. Can we look into this?
> 
> Why? Can you share the link to their official doc page?

It was a false flag, sorry for the trouble.
