### ISSUE TITLE
Shikimori tracking error

### ISSUE THREAD

**Issue by lv0-0vl** [aniyomiorg/aniyomi#696]
### Steps to reproduce

https://user-images.githubusercontent.com/104198703/181583602-3fc5aa2d-ee8c-498c-a559-83a1c2e57665.mp4

https://user-images.githubusercontent.com/104198703/181583611-2554acd2-dcc2-4186-9899-c30704c12e4c.mp4

https://user-images.githubusercontent.com/104198703/181583616-b1fded1c-35ae-4128-b33e-be43795bb07a.mp4

### Expected behavior

Add tracking 

### Actual behavior

Http error 404

### Aniyomi version

0.12.3.7

### Android version

10

### Device

Huawei P30 lite 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by GeorgyBuns** [comment]
Same issue, sadly

**Comment by Quickdesh** [comment]
Should be fixed
