### ISSUE TITLE
Anilist.co (tracking) error

### ISSUE THREAD

**Issue by KaiMaximus** [aniyomiorg/aniyomi#824]
### Steps to reproduce

![Screenshot_20221112-121727_Aniyomi](https://user-images.githubusercontent.com/101473761/201461438-b00b3ec6-3734-4081-a4b7-db7c2827a5c9.jpg)

### Expected behavior

![Uploading Screenshot_20221112-121858_Aniyomi.jpg…]()

### Actual behavior

Http error 429

### Crash logs

1)anime→select any anime→tracking→http error 429

### Aniyomi version

0.12.3.8

### Android version

Android 11

### Device

Samsung Galaxy A50

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.
